/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PackId = IDL.Nat64;
export const AttendanceRecord = IDL.Record({
  'status' : IDL.Text,
  'clientName' : IDL.Text,
  'date' : IDL.Text,
  'checkInTime' : IDL.Text,
  'packageDetails' : IDL.Text,
  'membershipId' : IDL.Text,
  'packageValidity' : IDL.Text,
  'checkOutTime' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Member = IDL.Record({
  'packageName' : IDL.Text,
  'status' : IDL.Text,
  'clientNo' : IDL.Text,
  'clientName' : IDL.Text,
  'membershipId' : IDL.Text,
  'packageValidity' : IDL.Text,
});
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Time = IDL.Int;
export const Pack = IDL.Record({
  'id' : PackId,
  'status' : Status,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIn' : IDL.Func([IDL.Text], [IDL.Text], []),
  'checkOut' : IDL.Func([IDL.Text], [IDL.Text], []),
  'createPack' : IDL.Func([IDL.Text, IDL.Text], [PackId], []),
  'getAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMemberById' : IDL.Func([IDL.Text], [IDL.Opt(Member)], []),
  'getMembers' : IDL.Func([], [IDL.Vec(Member)], []),
  'getPack' : IDL.Func([PackId], [IDL.Opt(Pack)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPacks' : IDL.Func([], [IDL.Vec(Pack)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePackStatus' : IDL.Func([PackId, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PackId = IDL.Nat64;
  const AttendanceRecord = IDL.Record({
    'status' : IDL.Text,
    'clientName' : IDL.Text,
    'date' : IDL.Text,
    'checkInTime' : IDL.Text,
    'packageDetails' : IDL.Text,
    'membershipId' : IDL.Text,
    'packageValidity' : IDL.Text,
    'checkOutTime' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Member = IDL.Record({
    'packageName' : IDL.Text,
    'status' : IDL.Text,
    'clientNo' : IDL.Text,
    'clientName' : IDL.Text,
    'membershipId' : IDL.Text,
    'packageValidity' : IDL.Text,
  });
  const Status = IDL.Variant({ 'active' : IDL.Null, 'inactive' : IDL.Null });
  const Time = IDL.Int;
  const Pack = IDL.Record({
    'id' : PackId,
    'status' : Status,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIn' : IDL.Func([IDL.Text], [IDL.Text], []),
    'checkOut' : IDL.Func([IDL.Text], [IDL.Text], []),
    'createPack' : IDL.Func([IDL.Text, IDL.Text], [PackId], []),
    'getAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMemberById' : IDL.Func([IDL.Text], [IDL.Opt(Member)], []),
    'getMembers' : IDL.Func([], [IDL.Vec(Member)], []),
    'getPack' : IDL.Func([PackId], [IDL.Opt(Pack)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPacks' : IDL.Func([], [IDL.Vec(Pack)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePackStatus' : IDL.Func([PackId, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };