/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Gym Attendance Manager API
 * OpenAPI spec version: 0.1.0
 */
import type { MemberStatus } from "./memberStatus";

export interface Member {
  membershipId: string;
  name: string;
  phone?: string;
  email?: string;
  package: string;
  startDate: string;
  expiryDate: string;
  status: MemberStatus;
  daysUntilExpiry: number;
  photoUrl?: string;
}
