/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Gym Attendance Manager API
 * OpenAPI spec version: 0.1.0
 */

export type MemberStatus = (typeof MemberStatus)[keyof typeof MemberStatus];

export const MemberStatus = {
  active: "active",
  expired: "expired",
  expiring_soon: "expiring_soon",
} as const;
